language: ruby

rvm:
        - 2.6.1

addons:
        postgresql: '9.6'

notifications:
        email: false

env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
                - CC_TEST_REPORTER_ID=a428acc14864346a703c3514c241e97f21c24a69ae6f6f25fb410687e76855ed

before_install: 
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.6
        - cd test/dummy
        - psql -c 'CREATE DATABASE sal7711gen_pru;' -U postgres
        - gem install bundler
        - gem update --system
        - bundle update --bundler
        - bundle install
        - cp config/database.travis.yml config/database.yml
        - cp db/structure.sql db/structure.sql.copia # travis no soporta PostreSQL 10
        - sed -e 's/provider = libc,//g' db/structure.sql.copia > db/structure.sql 
        - rake db:setup
        - rake sip:indices
        - cd ../..

script: 
        - bundle exec rails test -b

after_script:
        - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT

