require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Sal7711GenArticulosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Sal7711GenArticulo. As you add validations to Sal7711GenArticulo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Sal7711GenArticulosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sal7711_gen_articulos as @sal7711_gen_articulos" do
      sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sal7711_gen_articulo)).to eq([sal7711_gen_articulo])
    end
  end

  describe "GET #show" do
    it "assigns the requested sal7711_gen_articulo as @sal7711_gen_articulo" do
      sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
      get :show, {:id => sal7711_gen_articulo.to_param}, valid_session
      expect(assigns(:sal7711_gen_articulo)).to eq(sal7711_gen_articulo)
    end
  end

  describe "GET #new" do
    it "assigns a new sal7711_gen_articulo as @sal7711_gen_articulo" do
      get :new, {}, valid_session
      expect(assigns(:sal7711_gen_articulo)).to be_a_new(Sal7711GenArticulo)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sal7711_gen_articulo as @sal7711_gen_articulo" do
      sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
      get :edit, {:id => sal7711_gen_articulo.to_param}, valid_session
      expect(assigns(:sal7711_gen_articulo)).to eq(sal7711_gen_articulo)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Sal7711GenArticulo" do
        expect {
          post :create, {:sal7711_gen_articulo => valid_attributes}, valid_session
        }.to change(Sal7711GenArticulo, :count).by(1)
      end

      it "assigns a newly created sal7711_gen_articulo as @sal7711_gen_articulo" do
        post :create, {:sal7711_gen_articulo => valid_attributes}, valid_session
        expect(assigns(:sal7711_gen_articulo)).to be_a(Sal7711GenArticulo)
        expect(assigns(:sal7711_gen_articulo)).to be_persisted
      end

      it "redirects to the created sal7711_gen_articulo" do
        post :create, {:sal7711_gen_articulo => valid_attributes}, valid_session
        expect(response).to redirect_to(Sal7711GenArticulo.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sal7711_gen_articulo as @sal7711_gen_articulo" do
        post :create, {:sal7711_gen_articulo => invalid_attributes}, valid_session
        expect(assigns(:sal7711_gen_articulo)).to be_a_new(Sal7711GenArticulo)
      end

      it "re-renders the 'new' template" do
        post :create, {:sal7711_gen_articulo => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sal7711_gen_articulo" do
        sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
        put :update, {:id => sal7711_gen_articulo.to_param, :sal7711_gen_articulo => new_attributes}, valid_session
        sal7711_gen_articulo.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sal7711_gen_articulo as @sal7711_gen_articulo" do
        sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
        put :update, {:id => sal7711_gen_articulo.to_param, :sal7711_gen_articulo => valid_attributes}, valid_session
        expect(assigns(:sal7711_gen_articulo)).to eq(sal7711_gen_articulo)
      end

      it "redirects to the sal7711_gen_articulo" do
        sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
        put :update, {:id => sal7711_gen_articulo.to_param, :sal7711_gen_articulo => valid_attributes}, valid_session
        expect(response).to redirect_to(sal7711_gen_articulo)
      end
    end

    context "with invalid params" do
      it "assigns the sal7711_gen_articulo as @sal7711_gen_articulo" do
        sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
        put :update, {:id => sal7711_gen_articulo.to_param, :sal7711_gen_articulo => invalid_attributes}, valid_session
        expect(assigns(:sal7711_gen_articulo)).to eq(sal7711_gen_articulo)
      end

      it "re-renders the 'edit' template" do
        sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
        put :update, {:id => sal7711_gen_articulo.to_param, :sal7711_gen_articulo => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sal7711_gen_articulo" do
      sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
      expect {
        delete :destroy, {:id => sal7711_gen_articulo.to_param}, valid_session
      }.to change(Sal7711GenArticulo, :count).by(-1)
    end

    it "redirects to the sal7711_gen_articulo list" do
      sal7711_gen_articulo = Sal7711GenArticulo.create! valid_attributes
      delete :destroy, {:id => sal7711_gen_articulo.to_param}, valid_session
      expect(response).to redirect_to(sal7711_gen_articulos_url)
    end
  end

end
